job_environments:
    common_environment: &common_environment
      APP_HOSTPATH: gutenberg
      CONTAINER_PREFIX: planet4-gutenberg
      WP_DB_NAME_PREFIX: planet4-gutenber_wordpress
    develop_environment: &develop_environment
      APP_ENVIRONMENT: development
      APP_HOSTNAME: www-dev.greenpeace.org
      CLOUDSQL_INSTANCE: p4-develop-k8s
      GOOGLE_PROJECT_ID: planet-4-151612
      GCLOUD_CLUSTER: p4-development
      HELM_NAMESPACE: develop
      HELM_RELEASE: planet4-gutenberg
      NEWRELIC_APPNAME: P4 gutenberg Development
      WP_DB_NAME: planet4-gutenber_wordpress_develop
      WP_STATELESS_BUCKET: planet4-gutenberg-stateless-develop